run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - goimports
    - gosec
    - errorlint
    - gocritic
    - revive
    - cyclop

linters-settings:
  cyclop:
    max-complexity: 20
  
  errcheck:
    exclude-functions:
      - (io.Closer).Close
      - (*database/sql.Rows).Close
      - (*database/sql.Tx).Rollback
  
  gosec:
    excludes:
      - G404 

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gocritic
        - unparam
        - gosec
    
    - linters:
        - revive
      text: "stutters"
    
    - linters:
        - gocritic
      text: "builtinShadowDecl"
